# Generated by Django 4.2.5 on 2023-09-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_hoja_ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('estado', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='documento',
        ),
    ]
