# Generated by Django 4.2.5 on 2023-09-30 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejeapp', '0002_tipo_hoja_ruta_delete_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='hoja_ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('remitente', models.CharField(max_length=500)),
                ('referencia', models.CharField(max_length=500)),
                ('fechahora', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_tipohoja_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejeapp.tipo_hoja_ruta')),
            ],
        ),
    ]
