# Generated by Django 4.2.5 on 2023-09-30 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejeapp', '0003_hoja_ruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='remision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idusuario_origen', models.IntegerField()),
                ('idusuario_destino', models.IntegerField()),
                ('estado', models.CharField(choices=[('ev', 'Enviado'), ('pd', 'Pendiente'), ('re', 'Recibido')], default='ev', max_length=2)),
                ('habilitado', models.BooleanField(blank=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('nombres', models.CharField(max_length=500)),
                ('apellidos', models.CharField(max_length=500)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='hoja_ruta',
            name='prioritario',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='seguimiento_remision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idusuario_origen', models.IntegerField()),
                ('idusuario_destino', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('idremision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejeapp.remision')),
            ],
        ),
        migrations.AddField(
            model_name='remision',
            name='idhoja_ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejeapp.hoja_ruta'),
        ),
    ]
