# Generated by Django 4.2.5 on 2023-09-30 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejeapp', '0004_remision_usuario_hoja_ruta_prioritario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoja_ruta',
            old_name='id_tipohoja_ruta',
            new_name='tipohoja_ruta',
        ),
        migrations.RenameField(
            model_name='remision',
            old_name='idhoja_ruta',
            new_name='hoja_ruta',
        ),
        migrations.RenameField(
            model_name='seguimiento_remision',
            old_name='idremision',
            new_name='remision',
        ),
    ]
