# Generated by Django 4.2.5 on 2023-09-30 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejeapp', '0005_rename_id_tipohoja_ruta_hoja_ruta_tipohoja_ruta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='passwords',
        ),
    ]
