# Generated by Django 4.2.5 on 2023-10-06 19:31

from django.db import migrations, models
import ejeapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ejeapp', '0006_rename_password_usuario_passwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoja_ruta',
            name='numero',
            field=models.IntegerField(validators=[ejeapp.validators.validar_numero_hoja_ruta]),
        ),
        migrations.AlterField(
            model_name='tipo_hoja_ruta',
            name='descripcion',
            field=models.CharField(max_length=500, validators=[ejeapp.validators.validar_tipo_hoja_ruta]),
        ),
    ]
